# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7e4de491-506a-4167-8c00-d160cc7bf497";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5062-2E88";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

#   fileSystems."/var/lib/docker/overlay2/5d02213c082ce245cf8f51477afb02629a5e61088818ce5f115427c399423cf1/merged" =
#     { device = "overlay";
#       fsType = "overlay";
#     };
#
#   fileSystems."/var/lib/docker/overlay2/db96cbbfb9f3b30ca416451dfe27afded7533479df71e5869612e9e4f27cd670/merged" =
#     { device = "overlay";
#       fsType = "overlay";
#     };
#
#   fileSystems."/var/lib/docker/overlay2/422f0e12161e4eb2ab632d93368cfe48ceb57f6bf99ec02060263fa7e73c6ab6/merged" =
#     { device = "overlay";
#       fsType = "overlay";
#     };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-9e0f351eb829.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.vboxnet0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth13ba703.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2a75811.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth90f4098.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
